---
# tasks file for ./roles/updater

# SET TIMEZONE
- name: set timezone
  include: set_timezone.yml
  when: updater_config.set_timezone is defined and updater_config.set_timezone | bool

# SYNC TIME
- name: sync time
  include: sync_time.yml
  when: updater_config.sync_time is defined and updater_config.sync_time | bool

# SET LANGUAGE
- name: set language
  include: set_language.yml
  when: updater_config.set_language is defined and updater_config.set_language | bool

# ------------------------------------------------------------------------------
- name: updater - update repositories
  become: yes
  apt:
    update_cache: yes # equivalent of apt-get update
    force_apt_get: yes # apt-get instead of aptitude
    cache_valid_time: 3600
    autoremove: yes
    autoclean: yes
  when: updater_config.update_upgrade is defined and updater_config.update_upgrade | bool
  tags:
    - updater
    - update

- name: updater - upgrade packages
  become: yes
  apt:
    upgrade: dist # If yes or safe, performs an aptitude safe-upgrade.
    force_apt_get: yes # apt-get instead of aptitude
  when: updater_config.update_upgrade is defined and updater_config.update_upgrade | bool
  tags:
    - updater
    - upgrade
