---
# tasks file for ./roles/updater

# ------------------------------------------------------------------------------
- name: "UPDATER | apt | install dependencies"
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    force_apt_get: true # apt-get instead of aptitude
    update_cache: true
  loop: "{{ updater_dependencies | flatten(levels=1) }}"
  when:
    - updater_config.set_timezone is defined
    - updater_config.set_timezone | bool
  tags:
    - updater
    - dependencies

# ------------------------------------------------------------------------------
# SET TIMEZONE
- name: "UPDATER | time-zone | set timezone"
  ansible.builtin.include_tasks: set_timezone.yml
  when:
    - updater_config.set_timezone is defined
    - updater_config.set_timezone | bool

# SET TIME SYNC
- name: "UPDATER | time-sync | set time sync"
  ansible.builtin.include_tasks: set_time_sync.yml
  when:
    - updater_config.set_time_sync is defined
    - updater_config.set_time_sync | bool

# SET LANGUAGE
- name: "UPDATER | lang | set language"
  ansible.builtin.include_tasks: set_language.yml
  when:
    - updater_config.set_language is defined
    - updater_config.set_language | bool

- name: "UPDATER | lang-user | set language per user"
  ansible.builtin.include_tasks: set_language_user.yml
  loop: "{{ clients | flatten(levels=1) }}"
  loop_control:
    loop_var: outer_item
  when:
    - clients is defined
    - outer_item.locale is defined or outer_item.language is defined
    - updater_config.set_language is defined
    - updater_config.set_language | bool

# ------------------------------------------------------------------------------
- name: "UPDATER | apt | update repositories"
  become: true
  ansible.builtin.apt:
    update_cache: true # equivalent of apt-get update
    force_apt_get: true # apt-get instead of aptitude
    cache_valid_time: 3600
    autoremove: true
    autoclean: true
  when:
    - updater_config.update_upgrade is defined
    - updater_config.update_upgrade | bool
  tags:
    - updater
    - update

- name: UPDATER | apt | upgrade packages
  become: true
  ansible.builtin.apt:
    upgrade: dist # If yes or safe, performs an aptitude safe-upgrade.
    force_apt_get: true # apt-get instead of aptitude
  when:
    - updater_config.update_upgrade is defined
    - updater_config.update_upgrade | bool
  tags:
    - updater
    - upgrade

# ------------------------------------------------------------------------------
# SETUP ZFS
- name: "UPDATER | zfs | setup zfs"
  ansible.builtin.include_tasks: setup_zfs.yml
  when:
    - updater_config.setup_zfs is defined
    - updater_config.setup_zfs | bool

# ------------------------------------------------------------------------------
# SETUP UNATTENDED-UPGRADES
- name: "UPDATER | unattended | setup unattended-upgrades"
  ansible.builtin.include_tasks: unattended-upgrades.yml
  when:
    - updater_config.setup_unattended is defined
    - updater_config.setup_unattended | bool
