---
# tasks file for ./roles/updater

# ------------------------------------------------------------------------------
- name: "UPDATER | time-sync | install chosen time sync service ('chrony or systemd-timesyncd')"
  become: true
  ansible.builtin.apt:
    name: "{{ updater_ntp_serivce_use_time_synchronization_service }}"
    state: present
    force_apt_get: true
    update_cache: true
  tags:
    - updater
    - time-sync

# ------------------------------------------------------------------------------
- name: "UPDATER | time-sync | purge chrony if not chosen"
  become: true
  ansible.builtin.apt:
    name: chrony
    state: absent
    purge: true
  when:
    - updater_ntp_serivce_use_time_synchronization_service != "chrony"
  tags:
    - updater
    - time-sync

- name: "UPDATER | time-sync | mask + stop systemd-timesyncd if chrony chosen"
  become: true
  ansible.builtin.systemd_service:
    name: systemd-timesyncd.service
    daemon_reload: true
    enabled: false
    masked: true
    state: stopped
  failed_when: false # NOTE: sometimes throws error
  when:
    - updater_ntp_serivce_use_time_synchronization_service != "systemd-timesyncd"
  tags:
    - updater
    - time-sync

# ------------------------------------------------------------------------------
# SETUP NTP by timesyncd
- name: "UPDATER | time-sync | deploy timesyncd config '/etc/systemd/timesyncd.conf'"
  become: true
  ansible.builtin.template:
    src: timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    mode: "0644"
    owner: root
    group: root
  when:
    - updater_ntp_serivce_use_time_synchronization_service == "systemd-timesyncd"
  tags:
    - updater
    - time-sync
    - systemd-timesyncd

- name: "UPDATER | time-sync | restart systemd-timesyncd"
  become: true
  ansible.builtin.systemd_service:
    name: systemd-timesyncd
    daemon_reload: true
    masked: false
    enabled: true
    state: restarted
  when:
    - updater_ntp_serivce_use_time_synchronization_service == "systemd-timesyncd"
  tags:
    - updater
    - time-sync
    - systemd-timesyncd

# ------------------------------------------------------------------------------
# SETUP NTP by chrony
- name: "UPDATER | time-sync | deploy chrony config '/etc/chrony/chrony.conf'"
  become: true
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: "0644"
  when:
    - updater_ntp_serivce_use_time_synchronization_service == "chrony"
  tags:
    - updater
    - time-sync
    - chrony

- name: "UPDATER | time-sync | deploy chrony config '/etc/chrony/sources.d/ubuntu-ntp-pools.sources'"
  become: true
  ansible.builtin.template:
    src: chrony-ubuntu-ntp-pools.sources.j2
    dest: /etc/chrony/sources.d/ubuntu-ntp-pools.sources
    owner: root
    group: root
    mode: "0644"
  when:
    - updater_ntp_serivce_use_time_synchronization_service == "chrony"
  tags:
    - updater
    - time-sync
    - chrony

- name: "UPDATER | time-sync | restart chrony"
  become: true
  ansible.builtin.systemd_service:
    name: chrony
    daemon_reload: true
    masked: false
    enabled: true
    state: restarted
  when:
    - updater_ntp_serivce_use_time_synchronization_service == "chrony"
  tags:
    - updater
    - time-sync
    - chrony
    - molecule-idempotence-notest
