---
# tasks file for ./roles/updater

# ------------------------------------------------------------------------------
- name: "updater - ensure /etc/timezone contains {{ updater_time_timezone }}"
  become: true
  ansible.builtin.lineinfile:
    name: /etc/timezone
    line: "{{ updater_time_timezone }}"
    state: present
  check_mode: true
  register: checktimezone
  tags:
    - updater
    - timezone

- name: "updater - remove /etc/localtime"
  become: true
  ansible.builtin.file:
    path: "/etc/localtime"
    state: absent
  when: checktimezone.changed
  tags:
    - updater
    - timezone

- name: "updater - update /etc/timezone with {{ updater_time_timezone }}"
  become: true
  ansible.builtin.copy:
    content: "{{ updater_time_timezone }}"
    dest: "/etc/timezone"
    owner: root
    group: root
    mode: 0644
  notify: reconfigure tzdata
  when: checktimezone.changed
  tags:
    - updater
    - timezone
