---
# tasks file for ./roles/updater

# ------------------------------------------------------------------------------
- name: "UPDATER | time-zone | check for line in /etc/timezone with {{ updater_time_timezone }}"
  ansible.builtin.lineinfile:
    line: "{{ updater_time_timezone }}"
    path: /etc/timezone
  check_mode: true
  register: check_timezone
  tags:
    - updater
    - timezone

- name: "UPDATER | time-zone | update /etc/timezone with {{ updater_time_timezone }}"
  become: true
  ansible.builtin.copy:
    content: "{{ updater_time_timezone }}"
    dest: /etc/timezone
    owner: root
    group: root
    mode: "0644"
  register: timezone_changed
  when:
    - check_timezone is defined
    - check_timezone.changed | bool
  tags:
    - updater
    - timezone

- name: "UPDATER | time-zone | remove /etc/localtime"
  become: true
  ansible.builtin.file:
    path: "/etc/localtime"
    state: absent
  when:
    - timezone_changed is defined
    - timezone_changed.changed is defined
    - timezone_changed.changed | bool
  tags:
    - updater
    - timezone

- name: "UPDATER | time-zone | reconfigure tzdata"
  become: true
  ansible.builtin.command: dpkg-reconfigure -f noninteractive tzdata
  changed_when: false
  when:
    - timezone_changed is defined
    - timezone_changed.changed is defined
    - timezone_changed.changed | bool
  tags:
    - updater
    - timezone
