---
# tasks file for ./roles/updater

# ------------------------------------------------------------------------------
- name: "UPDATER | time-sync | install service 'chrony or systemd-timesyncd' as specified"
  become: true
  ansible.builtin.apt:
    name: "{{ updater_ntp_serivce_use_time_synchronization_service }}"
    state: present
    force_apt_get: true
    update_cache: true
  tags:
    - updater
    - time-sync

- name: "UPDATER | time-sync | remove chrony"
  become: true
  ansible.builtin.apt:
    name: chrony
    state: absent
    purge: true
  when:
    - updater_ntp_serivce_use_time_synchronization_service != "chrony"
  tags:
    - updater
    - time-sync

- name: "UPDATER | time-sync | mask systemd-timesyncd"
  become: true
  ansible.builtin.systemd_service:
    name: systemd-timesyncd.service
    daemon_reload: true
    enabled: false
    masked: true
    state: stopped
  failed_when: false # NOTE: sometimes throws error
  when:
    - updater_ntp_serivce_use_time_synchronization_service != "systemd-timesyncd"
  tags:
    - updater
    - time-sync

# ------------------------------------------------------------------------------
# SETUP NTP by timesyncd
- name: "UPDATER | time-sync | add/change /etc/systemd/timesyncd.conf"
  become: true
  ansible.builtin.template:
    src: timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    mode: "0644"
    owner: root
    group: root
  register: systemd_timesyncd_updated
  when:
    - updater_ntp_serivce_use_time_synchronization_service == "systemd-timesyncd"
  tags:
    - updater
    - time-sync
    - systemd-timesyncd

- name: "UPDATER | time-sync | restart systemd-timesyncd"
  become: true
  ansible.builtin.service:
    name: systemd-timesyncd
    state: restarted
    enabled: true
  when:
    - systemd_timesyncd_updated is defined
    - systemd_timesyncd_updated.changed is defined
    - systemd_timesyncd_updated.changed | bool
  tags:
    - updater
    - time-sync
    - systemd-timesyncd

# ------------------------------------------------------------------------------
# SETUP NTP by chrony
- name: "UPDATER | time-sync | add/change /etc/chrony/chrony.conf"
  become: true
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    mode: "0644"
    owner: root
    group: root
  register: chrony_updated
  when:
    - updater_ntp_serivce_use_time_synchronization_service == "chrony"
  tags:
    - updater
    - time-sync
    - chrony

- name: "UPDATER | time-sync | restart chrony"
  become: true
  ansible.builtin.service:
    name: chronyd
    state: restarted
    enabled: true
  when:
    - chrony_updated is defined
    - chrony_updated.changed is defined
    - chrony_updated.changed | bool
  tags:
    - updater
    - time-sync
    - chrony
