---
# tasks file for ./roles/updater

- name: "updater - creating and setup /etc/modprobe.d/zfs.conf"
  become: yes
  copy:
    dest: /etc/modprobe.d/zfs.conf
    content: |
      options zfs zfs_arc_min={{ ((ansible_memory_mb.real.total/4)*1024*1024)|round|int }}
      options zfs zfs_arc_max={{ ((ansible_memory_mb.real.total/2)*1024*1024)|round|int }}
  register: zfs_changes
  when: (ansible_memory_mb is defined and ansible_memory_mb.real is defined and ansible_memory_mb.real.total is defined)
  tags:
    - updater
    - sync_time

- name: "updater - re-init zfs changes"
  become: yes
  command: update-initramfs -u
  when: (zfs_changes is defined and zfs_changes.changed is defined and zfs_changes.changed|bool)
  tags:
    - updater
    - sync_time
