---
# tasks file for ./roles/updater

- name: "updater - creating and setup /etc/modprobe.d/zfs.conf"
  become: true
  shell: grep MemTotal /proc/meminfo | awk '{print $2}'
  register: node_memory_size
  tags:
    - updater
    - zfs

- name: "updater - creating and setup /etc/modprobe.d/zfs.conf"
  become: true
  copy:
    dest: /etc/modprobe.d/zfs.conf
    content: |
      options zfs zfs_arc_min={{ ((node_memory_size.stdout|int/4))|round|int }}
      options zfs zfs_arc_max={{ ((node_memory_size.stdout|int/2))|round|int }}
  register: zfs_changes
  when: (node_memory_size is defined and node_memory_size.stdout is defined)
  tags:
    - updater
    - zfs

- name: "updater - re-init zfs changes"
  become: true
  command: update-initramfs -u
  when: (zfs_changes is defined and zfs_changes.changed is defined and zfs_changes.changed|bool)
  tags:
    - updater
    - zfs
