---
# tasks file for ./roles/updater

# ------------------------------------------------------------------------------
- name: "UPDATER | sync-time | sync time step 1 - disable timedatectl ntp [set-ntp off]"
  become: true
  ansible.builtin.command: "timedatectl set-ntp off"
  register: timedatectl_off_output
  changed_when: timedatectl_off_output.rc != 0
  when: >
    (systemd_timesyncd_exist.stat is defined and systemd_timesyncd_exist.stat.exists | bool)
      or
    (chrony_exist.stat is defined and chrony_exist.stat.exists | bool)
  tags:
    - updater
    - sync_time

- name: "UPDATER | sync-time | sync time step 2 - activate timedatectl ntp [set-ntp on]"
  become: true
  ansible.builtin.command: "timedatectl set-ntp on"
  register: timedatectl_on_output
  changed_when: timedatectl_on_output.rc != 0
  when: >
    (systemd_timesyncd_exist.stat is defined and systemd_timesyncd_exist.stat.exists | bool)
      or
    (chrony_exist.stat is defined and chrony_exist.stat.exists | bool)
  tags:
    - updater
    - sync_time
