---
# tasks file for ./roles/updater
# <https://github.com/jnv/ansible-role-unattended-upgrades>

# ------------------------------------------------------------------------------
- name: "UPDATER | unattended | install unattended-upgrades"
  become: true
  ansible.builtin.apt:
    pkg:
      - unattended-upgrades
      - powermgmt-base
    state: present
    force_apt_get: true # apt-get instead of aptitude
    update_cache: true
  tags:
    - updater
    - unattended_upgrades

# ------------------------------------------------------------------------------
- name: "UPDATER | unattended | add distribution-specific variables"
  ansible.builtin.include_vars: "{{ ansible_distribution }}.yml"
  tags:
    - updater
    - unattended_upgrades

# ------------------------------------------------------------------------------
- name: "UPDATER | unattended | create APT auto-upgrades configuration"
  become: true
  ansible.builtin.template:
    src: auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: 0644
  tags:
    - updater
    - unattended_upgrades

- name: "UPDATER | unattended | create unattended-upgrades configuration"
  become: true
  ansible.builtin.template:
    src: unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: 0644
  tags:
    - updater
    - unattended_upgrades
