---
dependency:
  name: galaxy
driver:
  name: docker
lint: >
  set -e
  yamllint
  .ansible-lint
platforms:
  - name: instance
    image: mvladislav/docker-ubuntu-systemd-sudo-ansible:latest
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
    cgroupns: host
    privileged: True
    pre_build_image: True
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp
      remote_run: /run
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
