---
- name: Converge
  hosts: all
  gather_facts: true
  tasks:
    - name: "Run role"
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
